### PR TITLE
feat: new version of docs site

### PR DESCRIPTION
**Pull request by hannoeru**
- New layout
- New sidebar style
- Rewrite most CSS to Windi CSS
- Using Windi CSS Typography plugin to avoid css overwrite

### CODE REVIEW

**Comment by hannoeru** [comment]
https://deploy-preview-96--windicss.netlify.app/

**Comment by antfu** [comment]
Looks great, awesome work! I don't have strong opinion on styling as long as @voorjaar like them.

One thing tho, while I do think it's good for the new sidebar to be more compact, maybe we would want to have the consistent style for the TOC and dropdown menu (currently we have too many items, which becomes a bit hard to read)

👍

**Comment by harlan-zw** [comment]
The table of contents is great :ok_hand: 

Can we please fix the scrolling in this update? Not sure about it on other browsers but on chrome, there is no way to manually drag it, when you hover over it, it disappears (plus it's very difficult to see)

**Comment by harlan-zw** [comment]
Much better with the scroll now :tada: Nice job

**Comment by alexanderniebuhr** [comment]
nothing to say..

Looks amazing, can't wait to see it 🚀

**Pull request merged**
